### ISSUE TITLE
How to list all devices within a specific rack, or all racks within a specific site?

### ISSUE THREAD

**Issue by adamwoolhether** [ericgeldmacher/nbcli#15]
I think this is a great tool! The functionality/command is slightly unintuitive though. For example: how would list all the devices within a specific rack? Or all racks within a specific site, other than ```grep```  the output of ```nbcli pynb dcim.devices all``` ?

**Comment by ericgeldmacher** [comment]
Thanks for your interest in nbcli!
And congratulations on submitting the first issue!

Keep in mind that this project is still in development.  
Better documentation and help text is forthcoming, and the syntax of commands are subject to change.

To answer your specific example cases, the the `filter` method for the `pynb` command does accept keyword arguments to narrow the results.
* devices in rack
    ```
    $ nbcli pynb dcim.devices all
    ID  Name      Status  Tenant  Site    Rack     Role    Type   IP Address
    1   server01  Active  -       AMS 1   rack-01  server  Other  -
    2   server02  Active  -       AMS 2   rack-02  server  Other  -
    3   server03  Active  -       SING 1  rack-03  server  Other  -
    ```
    ```
    $ nbcli pynb dcim.devices filter rack_id=1
    ID  Name      Status  Tenant  Site   Rack     Role    Type   IP Address
    1   server01  Active  -       AMS 1  rack-01  server  Other  -
    ```
* racks at site
    ```
    $ nbcli pynb dcim.racks all
    ID  Name     Site    Group     Status  Facility ID  Tenant  Role    Height  Devices
    1   rack-01  AMS 1   -         Active  -            -       Role 1  47      1
    2   rack-02  AMS 2   -         Active  -            -       Role 2  47      1
    3   rack-03  SING 1  cage 101  Active  -            -       Role 3  47      1
    ```
    ```
    $ nbcli pynb dcim.racks filter site_id=1
    ID  Name     Site   Group  Status  Facility ID  Tenant  Role    Height  Devices
    1   rack-01  AMS 1  -      Active  -            -       Role 1  47      1
    ```
You can specify the same keyword multiple times to include more results
```
$ nbcli pynb dcim.devices filter rack_id=1 rack_id=2
ID  Name      Status  Tenant  Site   Rack     Role    Type   IP Address
1   server01  Active  -       AMS 1  rack-01  server  Other  -
2   server02  Active  -       AMS 2  rack-02  server  Other  -
```
```
$ nbcli pynb dcim.racks filter site_id=1 site_id=2
ID  Name     Site   Group  Status  Facility ID  Tenant  Role    Height  Devices
1   rack-01  AMS 1  -      Active  -            -       Role 1  47      1
2   rack-02  AMS 2  -      Active  -            -       Role 2  47      1
```

`pynb` is mostly just a command line wrapper for the [pynetbox](https://pynetbox.readthedocs.io/en/latest/) python module. (which is why its syntax can feel clunky)  
Have a familiarity with the pynetbox syntax and the NetBox REST API should help with its usage.

I should be able to utilize some of the logic I'm using in another command that I'm working on to help with the syntax of the existing commands.

So `$ nbcli pynb dcim.devices filter rack_id=1`  
could be expressed more like `$ nbcli pynb device filter rack:rack-01`  
(so the id would resolved for you and the appropriate keyword argument would be automatically added to the filter)

But that is still in the works.

**Comment by ericgeldmacher** [comment]
Created the following issues for follow up:
* #16 Documentation Improvements
* #17 Syntax Improvements.

**Comment by ericgeldmacher** [comment]
Closing this issue.
While they still need some fine tuning, the auto-resolve and compound resolve arguments for the filter command make this type of query much more straight forward.
And with me finally writing some documentation for the [filter](https://ericgeldmacher.github.io/nbcli/latest/commands/filter/) command, people might actually know how to use it.

To answer the original question now with using auto-resolve:
* list devices in racks
    ```
    nbcli filter device rack:$RACK_NAME
    ```
* list racks at site
    ```
    nbcli filter rack site:$SITE_NAME
    ```
